version: '3.9'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=
  servbyte:
    build: ./
    depends_on:
      - db
    ports:
      - 9009:8083

